builds:
  - main: main.go
    binary: devops-api
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
  - ldflags: -s -w -X "devops-api/common.BuildDate={{.Env.BUILD_DATE}}" -X "devops-api/common.CommitHash={{.Env.COMMIT_HASH}}" -X "devops-api/common.AppVersion={{.Env.APP_VERSION}}" -X "devops-api/common.GoVersion={{.Env.GO_VERSION}}"
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macos
    linux: linux